### ISSUE TITLE
[Question] How to use test annotations in monocart reports?

### ISSUE THREAD

**Issue by sevilla8623** [cenfun/monocart-reporter#4]
How to use test annotations in monocart reports the same as built-in html Playwright report? Annotations like skip, failed, or any custom annotations.

Thank you

**Comment by cenfun** [comment]
@sevilla8623 Thanks for reminding, I just released new version [1.0.8](https://www.npmjs.com/package/monocart-reporter/v/1.0.8) for custom annotations feature. please try it and let me know if any questions next.
btw. support markdown in description:
```js
// https://playwright.dev/docs/test-annotations#custom-annotations
test('test custom annotations', () => {
    test.info().annotations.push({
        type: 'issue',
        description: `## see github issues
- [monocart-reporter/issues](https://github.com/cenfun/monocart-reporter/issues)
- [playwright/custom-annotations](https://playwright.dev/docs/test-annotations#custom-annotations)
`
    });
});
```

**Comment by sevilla8623** [comment]
That is great! But after updating it to the 1.0.8 version, I have this error `Error: Cannot find module 'eight-colors'`
On v1.0.7 reporter works perfectly with the same tests.
Do you know what the issue might be?

**Comment by cenfun** [comment]
My mistake, the new version v1.0.9 has been released and added "eight-colors" dependence, please update again.

**Comment by sevilla8623** [comment]
The previous error is gone, but now I have another error `Error in reporter TypeError: The "id" argument must be of type string. Received undefined`
Do you know what is this?

**Comment by cenfun** [comment]
Sorry, I cannot find the root cause of the problem from this simple error message. Could you please provide more detailed information? like the steps to reproduce the problem, using cases or testing code. thanks

**Comment by cenfun** [comment]
please try v1.0.10 thanks

**Comment by sevilla8623** [comment]
The problem was with Playwright version. I used v1.25 and after updating to v1.28 everything start working fine. Thank you so much for the quick fixes.
